
- can be used to catch errors in async functions

```js
try {
let = y
const x = 2;
x = 3; 
} catch (err) {
alert(err.message);
}
```
